globalThis.facebookURL = "#";
globalThis.PinterestURL = "#";
globalThis.twitterURL = "#";
globalThis.redditURL = "#";
globalThis.siteUrl = "https:\/\/www.allsnackrecipes.com";
globalThis.homepageTitle = "All Snack Recipes";
globalThis.homepageTagline = "Easy high-protein snack recipes to fuel your day. Discover no-bake protein  balls, cottage cheese bowls, and meal-prep snacks made simple and delicious.";
globalThis.email = 'contact@myrecipes.com';
globalThis.copyright = "2025 - 2026 All Snack Recipes. All rights reserved.";
