globalThis.facebookURL = "#";
globalThis.PinterestURL = "#";
globalThis.twitterURL = "#";
globalThis.redditURL = "#";
globalThis.siteUrl = "https:\/\/www.allsnackrecipes.com";
globalThis.homepageTitle = "All Snack Recipes";
globalThis.homepageTagline = "All Snack Recipes - Discover delicious recipes for every occasion";
globalThis.email = 'contact@myrecipes.com';
globalThis.copyright = "2025 - 2026 All Snack Recipes. All rights reserved.";
